__init__.py
from flask import Flask
from routes.home import home_route
from routes.ganhos import ganhos_route
from routes.despesas import despesas_route
from routes.login import login_route

app=Flask(__name__); 
app.secret_key = 'your_secret_key'  
app.register_blueprint(home_route)
app.register_blueprint(ganhos_route, url_prefix='/ganhos')
app.register_blueprint(despesas_route, url_prefix='/despesas')
app.register_blueprint(login_route, url_prefix='/login')


app.run(debug=True)

routes/despesas.py
from flask import Blueprint, jsonify, redirect, render_template, request, url_for
from database.db import despesas, saldo
despesas_route = Blueprint("despesas", __name__)

@despesas_route.route('/')
def listardespesas():
    return render_template('despesas.html', despesas=despesas, saldo=saldo)

@despesas_route.route('/', methods=['POST'])
def inserirdespesas():
    global saldo
    nova_despesa={
        "id": len(despesas) +1,
        "value": float(request.form.get('valor')),
        "class": request.form.get('categoria'),
        "date": request.form.get('data')
    }
    despesas.append(
        nova_despesa
    )
    saldo -= nova_despesa["value"]
    return render_template("despesas.html", despesas=despesas, saldo=saldo)

@despesas_route.route('/<int:despesa_id>/delete', methods=['DELETE'])
def deletardespesas(despesa_id):
    global despesas
    global saldo
    
    print("despesas antes da deleção:", despesas)
    
    for i in despesas:
        if despesa_id == i['id']:
            saldo += i['value']
    
    despesas = [u for u in despesas if u['id'] != despesa_id]
    print("despesas após a deleção:", despesas)

    # Retorne um JSON com o novo saldo
    return jsonify({"deleted": "ok", "novo_saldo": saldo})

routes/ganhos.py
from flask import Blueprint, jsonify, redirect, render_template, request, url_for
from database.db import ganhos, saldo
ganhos_route = Blueprint("ganhos", __name__)

@ganhos_route.route('/')
def listarganhos():
    return render_template('ganhos.html', ganhos=ganhos, saldo=saldo)

@ganhos_route.route('/', methods=['POST'])
def inserirganhos():
    global saldo
    novo_ganho={
        "id": len(ganhos) +1,
        "value": float(request.form.get('valor')),
        "class": request.form.get('categoria'),
        "date": request.form.get('data')
    }
    ganhos.append(
        novo_ganho
    )
    saldo += novo_ganho["value"]
    return render_template("ganhos.html", ganhos=ganhos, saldo=saldo)

@ganhos_route.route('/<int:ganho_id>/delete', methods=['DELETE'])
def deletarGanhos(ganho_id):
    global ganhos
    global saldo
    
    print("Ganhos antes da deleção:", ganhos)
    
    for i in ganhos:
        if ganho_id == i['id']:
            saldo -= i['value']
    
    ganhos = [u for u in ganhos if u['id'] != ganho_id]
    print("Ganhos após a deleção:", ganhos)

    # Retorne um JSON com o novo saldo
    return jsonify({"deleted": "ok", "novo_saldo": saldo})

routes/home.py
from flask import Blueprint, render_template
from database.db import saldo
home_route = Blueprint("home", __name__)

@home_route.route('/')
def home():
    return render_template('home.html', saldo=saldo)

routes/login.py
from flask import Blueprint, jsonify, render_template, request, redirect, url_for, session
from database.db import users, saldo

login_route = Blueprint("login", __name__)

@login_route.route('/')
def login():
    error_message = session.get('error')
    session.pop('error', None) 
    return render_template('login.html', error=error_message)

@login_route.route('/autenticar', methods=['GET'])
def autenticar():
    usuario = request.args.get('usuariologin')
    passw = request.args.get('passwlogin')
    
    session.pop('error', None)  
    print(usuario, users)
    if usuario in users:
        if users[usuario] == passw:
            return render_template('home.html', saldo=saldo)
        else:
            session['error'] = "Senha incorreta. Tente novamente."
    else:
        session['error'] = "Usuário não encontrado."
    
    return redirect(url_for('login.login'))

@login_route.route('/new', methods=['GET'])
def register():
    return render_template('home.html', saldo=saldo)

@login_route.route('/dados', methods=['GET'])
def obter_dados():
    return jsonify(users)

templates/despesas.html
{% extends 'header.html' %}
{% block conteudo %} 

<div class="grid">
    {% for d in despesas %}
        {% include 'itemDespesas.html' %}
    {% endfor %}
</div>

<div id="popup" class="popup-container">
    <div class="popup-content">
        <h2>NOVAS DESPESAS</h2>
        <p>Cadastre suas Despesas</p>
        <form class="c-form" action="{{url_for('despesas.inserirdespesas')}}" method="post">
            <input type="number" min="0" step="0.01" id="valor" name="valor" placeholder="Digite o valor">

            <input type="text" id="categoria" name="categoria" placeholder="Digite a categoria">

            <input type="date" id="data" name="data">
            
            <button type="button" class="caddespesas">Cadastrar</button>
        </form>
        <button class="close-popup-btn" onclick="closePopup()">Fechar</button>
    </div>
</div>
<div id="snackbar" class="snackbar"></div>

<script src="../static/cru.js"></script>
<script>
    const add = document.querySelector(".add");
    add.style.display = "block";
    const caddespesas = document.querySelector(".caddespesas");

    add.addEventListener("click", function (){
        openPopup();
    });
    caddespesas.addEventListener("click", function (){
        console.log("clique")
        verifydespesas();
    });
    function openPopup() {
        document.getElementById("popup").style.display = "flex";
    }

    function closePopup() {
        document.getElementById("popup").style.display = "none";

    }
    function showSnackbar(message) {
    const snackbar = document.getElementById("snackbar");
    snackbar.innerText = message;
    snackbar.className = "snackbar show";
    document.getElementById("valor").focus();
    setTimeout(() => {
        snackbar.className = snackbar.className.replace("show", "");
    }, 4000);

   
    
}

    function verifydespesas() {
        let form = document.querySelector("form")
        let valor = parseFloat(document.getElementById("valor").value);
        let categoria = document.getElementById("categoria").value;
        let data = document.getElementById("data").value;
        console.log("Valor:", valor);
        console.log("Categoria:", categoria);
        console.log("Data:", data);
        if(valor && categoria && data){
            console.log("valido");
            form.submit();
        } else {
            showSnackbar("Preencha todos os campos");
        }
    }
</script>
{% endblock %}

templates/ganhos.html
{% extends 'header.html' %}
{% block conteudo %} 

<div class="grid">
    {% for g in ganhos %}
        {% include 'itemGanhos.html' %}
    {% endfor %}
</div>

<div id="popup" class="popup-container">
    <div class="popup-content">
        <h2>NOVOS GANHOS</h2>
        <p>Cadastre seus ganhos</p>
        <form class="c-form" action="{{url_for('ganhos.inserirganhos')}}" method="post">
            <input type="number" min="0" step="0.01" id="valor" name="valor" placeholder="Digite o valor">

            <input type="text" id="categoria" name="categoria" placeholder="Digite a categoria">

            <input type="date" id="data" name="data">
            
            <button type="button" class="cadganhos">Cadastrar</button>
        </form>
        <button class="close-popup-btn" onclick="closePopup()">Fechar</button>
    </div>
</div>
<div id="snackbar" class="snackbar"></div>

<script src="../static/cru.js"></script>
<script>
    const add = document.querySelector(".add");
    add.style.display = "block";
    const cadganhos = document.querySelector(".cadganhos");

    add.addEventListener("click", function (){
        openPopup();
    });
    cadganhos.addEventListener("click", function (){
        console.log("clique")
        verifyGanhos();
    });
    function openPopup() {
        document.getElementById("popup").style.display = "flex";
    }

    function closePopup() {
        document.getElementById("popup").style.display = "none";

    }
    function showSnackbar(message) {
    const snackbar = document.getElementById("snackbar");
    snackbar.innerText = message;
    snackbar.className = "snackbar show";
    document.getElementById("valor").focus();
    setTimeout(() => {
        snackbar.className = snackbar.className.replace("show", "");
    }, 4000);

   
    
}

    function verifyGanhos() {
        let form = document.querySelector("form")
        let valor = parseFloat(document.getElementById("valor").value);
        let categoria = document.getElementById("categoria").value;
        let data = document.getElementById("data").value;
        console.log("Valor:", valor);
        console.log("Categoria:", categoria);
        console.log("Data:", data);
        if(valor && categoria && data){
            console.log("valido");
            form.submit();
        } else {
            showSnackbar("Preencha todos os campos");
        }
    }
</script>
{% endblock %}

templates/header.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nome do site</title>
    <link rel="stylesheet" href="../static/css/header.css">
    <link rel="stylesheet" href="../static/css/home.css">
    <link rel="stylesheet" href="../static/css/ganhos.css">
    <link rel="stylesheet" href="../static/css/despesas.css">
</head>
<body>
    <header>
        <div class="space"></div>
        <a href="{{ url_for('home.home') }}" type="block" style="text-decoration: none;">
        <div class="logo">
            <img id="imglogo" src="../static/images/logo.png" alt="">
        </div>
        </a>
        <div class="perfil">
            <img src="../static/images/perfil.png" alt="" class="user">
            <img src="../static/images/adicionar.png" alt="" class="add">
        </div>
    </header>
        <div class="valor-conteiner">
            <div class="valor">
                <div class="divvalortotal"><h2>{{'R${:.2f}'.format(saldo) }}</h2></div>
                <div class="divolho"><img id="imgolho" src="../static/images/olho.png" alt=""></div>
            </div>
        </div>
        {% block conteudo %}{% endblock %}
        
</body>
</html>

templates/home.html
{% extends 'header.html' %}
{% block conteudo %} 
<div class="cards">
    <a href="{{ url_for('ganhos.listarganhos') }}" type="block" style="text-decoration: none;">
        <div class="cardganhos">
            <img id="imgganhos" src="../static/images/moeda.png" alt="">
            <p>Ganhos</p>
        </div>
    </a>
    <a href="{{ url_for('despesas.listardespesas') }}" type="block" style="text-decoration: none;">
        <div class="carddespesas">
            <img id="imgdespesas" src="../static/images/cartao.png" alt="">
            <p>Despesas</p>
        </div>
    </a>
    <div class="cardmoedas">
        <img id="imgmoedas" src="../static/images/config.png" alt="">
        <p>Moedas</p>
    </div>
</div>
{% endblock %}

templates/itemDespesas.html
<div class="despesa">
    <h2>{{ 'R$-{:.2f}'.format(d.value) }}</h2>
    <div class="dsection">
        <div class="dtext">
            <p>Data: {{d.date}}</p>
            <p>Categoria: {{d.class}}</p>
        </div>
        <button class="delete" c-delete="{{url_for('despesas.deletardespesas', despesa_id=d.id)}}" c-remove-closest=".despesa"><img src="../static/images/delete.png" alt=""></button>
    </div>
</div>

templates/itemGanhos.html
<div class="ganho">
    <h2>{{ 'R${:.2f}'.format(g.value) }}</h2>
    <div class="gsection">
        <div class="gtext">
            <p>Data: {{g.date}}</p>
            <p>Categoria: {{g.class}}</p>
        </div>
        <button class="delete" c-delete="{{url_for('ganhos.deletarGanhos', ganho_id=g.id)}}" c-remove-closest=".ganho"><img src="../static/images/delete.png" alt=""></button>
    </div>
</div>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/css/style.css">
    <link rel="stylesheet" href="../static/css/login.css">
    <script src="../static/js/login.js" defer></script>
    <title>Login</title>
</head>
<body>
    <div class="all">
        <div class="left">
            <form action="{{ url_for('login.autenticar') }}" id="form-left" method="GET">
                <h1 style="color: white;">{% if error %} {{error}} {% else %} BEM-VINDO! {% endif %}</h1>
            
                <div class="inputs" id="lfi">
                    <input accept="all" type="text" class="base_input" placeholder="Usuário" name="usuariologin">
                    <input type="password" class="base_input" placeholder="Senha" name="passwlogin">
                </div>
            
                <div class="logo logoleft"><img src="../static/images/cifrao.png" alt=""></div>
            
                <button class="white_base_button" type="button" onclick="loginb()">Login</button>
            </form>
        </div>
        <div class="right">
            <form action="{{ url_for('login.register') }}" id="form-right">
            <h1 class="title">Crie uma conta</h1>
            <div class="inputs" id="rgi">
                <input type="text" class="base_input" placeholder="Usuário" name="usuario">
                <input type="password" class="base_input" placeholder="Senha" name="senha">
            </div>
            <div class="logo logoright"><img src="../static/images/cifrão2.png" alt=""></div>
            
            <div class="box-cad">
                <button class="green_base_button" onclick="cadb()" type="button">Cadastrar</button>
            </div>
            </form>
        </div>
    </div>
    <div id="snackbar" class="snackbar"></div>
</body>
</html>

templates/nav.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body> 
    {% block conteudo %}{% endblock %}
</body>
</html>